version: '3.4'

services:
  server:
    image: ghcr.io/goauthentik/server:2024.6.1
    container_name: auth-server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST}
      AUTHENTIK_POSTGRESQL__HOST: ${DB_HOST}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - ./configs/media:/media
      - ./configs/templates:/templates
    ports:
      - "9000:9000"
    networks:
      - proxy

  worker:
    image: ghcr.io/goauthentik/server:2024.6.1
    container_name: auth-worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST}
      AUTHENTIK_POSTGRESQL__HOST: ${DB_HOST}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - ./configs/media:/media
      - ./configs/templates:/templates
    networks:
      - proxy

networks:
  proxy:
    external: true
